# Site settings
title         : Aesop's Fables
description   : Using Aesop's Fables to demonstrate Jekyll functionality.
url           : "http://tylercampbell.github.io"
baseurl       : "/jekyll-starter-kit"

# Color variable for Android & Windows tiles
color         : "#2F3BA2"

# Permalinks
permalink     : pretty
paginate      : 2
paginate_path : '/updates/page:num'

# Filtering Content
future        : false
show_drafts   : false
limit_posts   : 0

# Gives you more accurate related posts
lsi           : false

# Sass
sass          :
  sass_dir    : assets/sass
  style       : compressed

# Collections
collections   :
  fables      :
    output    : true
    permalink : /fables/:path/

defaults      :
  -
    scope     :
      path    : "" # an empty string here means all files in the project
    values    :
      layout  : "default"
  -
    scope     :
      path    : ""
      type    : "fables" # the fables collection
    values    :
      layout  : "fable" # will default to the fable layout

# Pagination
gems:
  - jekyll-paginate

# Exclude
exclude       : [bower_components, node_modules, gulpfile.js, package.json]
