# Site settings
title: Aesop's Fables
description: Using Aesop's Fables to demonstrate Jekyll functionality.
url: "http://tylercampbell.github.io"
baseurl: "/jekyll-starter-kit"

# Color variable for Android & Windows tiles
color: "#2F3BA2"

# Permalinks
permalink          : pretty
paginate           : 10
paginate_path      : '/news/page:num'
excerpt_separator  : '<!--more-->'

# Build settings
markdown: kramdown

# Show drafts and future posts?
future             : false
show_drafts        : false

# Gives you more accurate related posts
lsi                : false
limit_posts        : 0


# Sass
sass:
  sass_dir: assets/sass
  style: compressed

# Collections
collections:
  fables:
    output: true
    permalink: /fables/:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "fables" # the fables collection
    values:
      layout: "fable" # will default to the fable layout

# Exclude
exclude: [bower_components, node_modules, gulpfile.js, package.json]
